### ISSUE TITLE
Test on Church lot track

### ISSUE THREAD

**Issue by subhash** [subhash/CarND-Capstone#9]
The simulator also includes the track on which Carla will be tested on. To test using this, change `waypoint_loader.launch` to the following:

```
<?xml version="1.0"?>
<launch>
    <node pkg="waypoint_loader" type="waypoint_loader.py" name="waypoint_loader">
        <param name="path" value="$(find styx)../../../data/churchlot_with_cars.csv" />
        <param name="velocity" value="10" />
    </node>
</launch>
```

**Comment by subhash** [comment]
I tested this track and it works fine if line 60 in `waypoint_updater` is modified thus:
`            next_wp = self.next_waypoint(self.pose.position, self.pose.orientation, self.next_wp)` to 
`            next_wp = self.next_waypoint(self.pose.position, self.pose.orientation)`

This is because the track is circular, but I think we are not considering our waypoint list that way. 

![site-track-wp](https://user-images.githubusercontent.com/87746/37072974-1f2ba448-21ea-11e8-985b-9e12effa5e8f.png)

**Comment by volkodava** [comment]
@subhash yep, but from another side I didn't see that car should make 1 and more circles around the track, but if you think it make sense we can avoid passing `around_wp` parameter so that car will drive next circles with no issue, right.

**Comment by volkodava** [comment]
@subhash pull request for this task at: https://github.com/subhash/CarND-Capstone/pull/13

**Comment by subhash** [comment]
@volkodava, we cannot get rid of around_wp, because in the simulated track, there are too many waypoints and including all waypoints will increase the computation. My code was just for demonstrating the problem.

When we use around_wp, we are blindly looking for 20 or so points ahead of it. If we come to the end of the list of waypoints while taking these 20, there's a failure. Instead we should consider the list as circular and if we come to the end of the list, we should start from the beginning of the list.

**Comment by subhash** [comment]
A way to test for heavy computation is to get rid of around_wp and test on
the simulated track. After a while, with camera on, the waypoint path will
start dragging behind the car and the car will slowly go adrift

**Comment by volkodava** [comment]
@subhash sure, this issue should be fixed already: https://github.com/subhash/CarND-Capstone/pull/13 Could you review it?
